# 산포통계

In [1]:
import numpy as np
from scipy import stats
import pandas as pd

### 분산 계산

In [2]:
x = [1, 2, 3, 4, 5]
print(np.var(x, ddof = 1)) 
print(np.array(x).var())

print(pd.Series(x).var(ddof = 0))

2.5
2.0
2.0


### 표준편차 계산

In [3]:
x = [1, 2, 3, 4, 5]
print(np.std(x, ddof = 1))
print(np.array(x).std(ddof = 0))
print(pd.Series(x).std(ddof = 1))

1.5811388300841898
1.4142135623730951
1.5811388300841898


### 변동 계수의 필요성
- 분산과 표준편차 모두 값의 스케일에 크게 영향을 받아 상대적인 산포를 보여주는데 부적합함.
- 변동 계수 = 표준편차 / 평균

In [4]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

print(np.std(x1, ddof = 1))
print(np.std(x2, ddof = 1 ))

1.5811388300841898
15.811388300841896


In [5]:
print(stats.variation(x1))
print(stats.variation(x2))

0.47140452079103173
0.4714045207910317


In [8]:
print(np.std(x1, ddof = 1) / np.mean(x1))
print(np.std(x2, ddof = 1) / np.mean(x2))

0.5270462766947299
0.5270462766947299


# 스케일링
- 둘 이상의 변수의 값을 상대적으로 비교할 때 사용

In [9]:
import numpy as np
import pandas as pd

In [10]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

In [11]:
x1

array([1, 2, 3, 4, 5])

In [12]:
x2

array([10, 20, 30, 40, 50])

In [14]:
z1 = (x1 - x1.mean()) / x1.std()
z2 = (x2 - x2.mean()) / x2.std()

print(z1)
print(z2)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [16]:
z1 = (x1 - x1.min()) / (x1.max() - x1.min())
z2 = (x2 - x2.min()) / (x2.max() - x2.min())

print(z1)
print(z2)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]


In [17]:
X = pd.DataFrame({"X1":[1, 2, 3, 4, 5],
                  "X2":[10, 20, 30, 40, 50]})
X

,X1,X2
0,1,10
1,2,20
2,3,30
3,4,40
4,5,50


In [18]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
Z = scaler.fit_transform(X)
pd.DataFrame(Z, columns=['X1', 'X2'])

,X1,X2
0,0.00,0.00
1,0.25,0.25
2,0.50,0.50
3,0.75,0.75
4,1.00,1.00


In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
ss_scaler = StandardScaler()
Z = ss_scaler.fit_transform(X)
pd.DataFrame(Z, columns=['X1', 'X2'])

,X1,X2
0,-1.414214,-1.414214
1,-0.707107,-0.707107
2,0.000000,0.000000
3,0.707107,0.707107
4,1.414214,1.414214


In [ ]:
ss_scaler = StandardScaler()
S = ss_scaler.fit_transform(X)
pd.DataFrame(S, columns=['X1', 'X2'])

,X1,X2
0,-1.414214,-1.414214
1,-0.707107,-0.707107
2,0.000000,0.000000
3,0.707107,0.707107
4,1.414214,1.414214


: 